### PR TITLE
minor tweaks to manufacturer #218

### LINKED ISSUE #218: minor tweaks to Manufacturer
- On the catalogue item landing page the address format should be the same as the table : 
<br><br>

image
<br><br>

currently it looks like this:

<br><br>
image

same in the details panel
<br><br>

image

- The styling is wrong on the landing page:(using yarn serve:build for IMS)

image

### PR DESCRIPTION
**Pull request by MatteoGuarnaccia5**
## Description

Tweaked landing pages and details panel in catalogue items for the manufacturer address.
Changed styling on manufacturer page so looks as it should in production

## Testing instructions

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] check catalogue items landing page & details panel
- [ ] check manufacturer landing page after using `yarn serve:build`

## Agile board tracking

closes #218

### CODE REVIEW

**Review by joshuadkitenge — CHANGES_REQUESTED** [review]
Can you also remove the listitem from the details panel please

File: src/catalogue/items/CatalogueItemsDetailsPanel.component.tsx [hunk 1]
```diff
@@ -187,26 +187,15 @@ function CatalogueItemsDetailsPanel(props: CatalogueItemsDetailsPanelProps) {
...
-                          index
-                        ].unit
-                          ? `(${catalogueCategoryData?.catalogue_item_properties?.[index].unit})`
-                          : ''
-                      }`}
-                      secondary={String(property.value)}
-                    />
-                  </ListItem>
+                  <Typography color="text.primary">{`${property.name} ${
+                    catalogueCategoryData?.catalogue_item_properties?.[index]
```
Comment (joshuadkitenge) [inline src/catalogue/items/CatalogueItemsDetailsPanel.component.tsx:191]: can you change the unit to match was is being done on the landing page please.

```

                <Typography align="left" color="text.primary">{`${
                            property.name
                          } ${
                            property.unit ? `(${property.unit})` : ''
                          }`}</Typography>
                          <Typography align="left" color="text.secondary">
                            {String(property.value)}
                          </Typography>
```

**Review by joshuadkitenge — CHANGES_REQUESTED** [review]

File: src/manufacturer/manufacturerLandingPage.component.tsx [hunk 2]
```diff
@@ -63,66 +63,67 @@ function ManufacturerLandingPage() {
...
-              <Typography sx={{ margin: 1, textAlign: 'center' }} variant="h4">
-                {manufacturerData.name}
+        <Grid
+          container
+          spacing={1}
+          sx={{ px: '192px' }}
+          alignContent={'center'}
+          flexDirection="row"
+        >
+          <Grid item xs={12}>
```
Comment (joshuadkitenge) [inline src/manufacturer/manufacturerLandingPage.component.tsx:73]: - can you change the non-header text to to use color={'text.secondary'} , for the url, telephone number and address. 
<br>
EXAMPLE:

```
  <Grid item xs={12} my={2}>
            <Typography textAlign={'center'} variant="h6">
              Telephone number:
            </Typography>
          </Grid>
          <Grid item xs={12}>
            <Typography sx={{ mx: '8px' }} textAlign={'center'} variant="body1" color="text.secondary">
              {manufacturerData.telephone}
            </Typography>
          </Grid>
```
<br>

- can you also default the values to 'None' if they don't exist on the manufacturers landing page.

<br>

- add the manufacturer telephone number to the catalogue item landing page and catalogue details panel.

**Review by joshuadkitenge — CHANGES_REQUESTED** [review]

**Review by joshuadkitenge — CHANGES_REQUESTED** [review]
The address values shouldn't default to none as the object properties have  mandatory values. 

- remove `?? 'None'` for the address properties 
image

**Review by joshuadkitenge — APPROVED** [review]
