### PR TITLE
Spares filter button (Bug) #1588

### LINKED ISSUE #1588: Spares filter button (Bug)
The spares button on the items table only work on page 1

### PR DESCRIPTION
**Pull request by joshdimanteto**
## Description

Create a separate banner for spares, as the bottom banner was need for grouped by columns 
The spares banner wasn't applied when non columns filter state value were modified such as pagination and grouping. It should be visible e.g. page 2 or group by assets number   

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
closes #1588

### CODE REVIEW

File: src/items/itemsTable.component.tsx [hunk 1]
```diff
@@ -756,15 +739,64 @@ export function ItemsTable(props: ItemTableProps) {
...
+            p: 0,
+            position: 'relative',
+            right: 0,
+            top: 0,
+            width: '100%',
+            zIndex: 2,
+          })}
+        >
+          <Grid container alignItems="center" sx={{ px: 1, py: 0.5 }}>
+            <Grid size={2}> </Grid>
```
Comment (joelvdavies) [inline src/items/itemsTable.component.tsx]:
```suggestion
            <Grid size={2} />
```
Same comment as before, I suspect it should fix itself when merged though.

**Review by joelvdavies — COMMENTED** [review]
Fixed the issue I found with the page numbers effecting it. Didnt find anything else. Only comment was same as saw on the other PR so will probably be fixed when merged anyway.

**Comment by joshdimanteto** [comment]
```
    muiToolbarAlertBannerProps: {
      sx: {
        '& .MuiAlert-message': {
          maxWidth: undefined,
          width: '100%',
        },
      },
    },
```

remove

**Review by joelvdavies — DISMISSED** [review]
LGTM

**Review by joelvdavies — APPROVED** [review]
