### PR TITLE
Fix: Grouping by Id instead of name and include expected Lifetime days in the table #1278

### LINKED ISSUE #1278: systems items table (demo prep)
- The grouping should be done by `Id` and it is currently being done by name.
- The expected Lifetime days should also be included in this table

### LINKED ISSUE #1280: no properties message to landing pages and details panels
Image

Image

### PR DESCRIPTION
**Pull request by joshdimanteto**
## Description
see #1278 #1280

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking

closes #1278, closes #1280

### CODE REVIEW

**Comment by joshuadkitenge** [comment]
Add test later

File: src/systems/systemItemsTable.component.tsx [hunk 1]
```diff
@@ -545,6 +546,24 @@ export function SystemItemsTable(props: SystemItemsTableProps) {
...
+        size: 300,
+        AggregatedCell: ({ cell, table }) => {
+          const isCatalogueGrouped = table
+            .getState()
+            .grouping.includes('catalogueItem.name');
+          const isCatalogueItemRow =
+            cell.row.groupingColumnId === 'catalogueItem.name';
+          return (
+            isCatalogueGrouped &&
+            isCatalogueItemRow && <>{cell.getValue<number>()}</>
```
Comment (rowan04) [inline src/systems/systemItemsTable.component.tsx:563]:
```suggestion
            isCatalogueItemRow &&
            <>{cell.getValue<number>()}</>
```
small change, not really necessary but

**Review by rowan04 — COMMENTED** [review]
small comment, else looks good! I also wonder if the title of the PR could be improved, e.g. including the word systems, and maybe mentioning the properties.length changes in description

**Comment by joshdimanteto** [comment]
> small comment, else looks good! I also wonder if the title of the PR could be improved, e.g. including the word systems, and maybe mentioning the properties.length changes in description

I forgot to tag the other issue here it is #1280. The other suggestion is a prettier change so the formatting is expected. The pr is fine

**Review by rowan04 — APPROVED** [review]
lgtm!
